name: create tag

on:
  push
jobs:
  merge-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.repos.compareCommits({
              context.repo.owner,
              context.repo.repo,
              "initial-tag",
              "master"
            });
            console.log(response)