name: merge-list

on:
  push
jobs:
  merge-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "initial-tag",
              head: "master"
            });

            const pullRequestList = response.data.commits.reduce((acc, cur) => {
              const [title, , ...body] = cur.commit.message.split('\n');
              const result = title.match(/Merge pull request #(.)/);
              if (result) {
                acc.push({
                  author: cur.commit.author.name,
                  pullRequestNumber: result[1],
                  message: body[0],
                });
              }
              return acc;
            }, []);
            console.log(pullRequestList);

            let body = [];
            body.push('# テストリリースのbody');
            body.push('## リリース内容');
            body.push('| プルリク | 内容 |');
            body.push('| -- | -- |');
            pullRequestList.forEach(({ pullRequestNumber, message }) => {
              body.push(`| ${pullRequestNumber} | ${message} |`);
            });
            console.log(body.join('\n'));
      - name: Slack Notification
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Hello, Slack!