name: merge-list

on:
  push
jobs:
  merge-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const response = await github.repos.compareCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "initial-tag",
              head: "master"
            });

            const pullRequestList = response.data.commits.reduce((acc, cur) => {
              console.log(cur);
              const [title, , ...body] = cur.commit.message.split('\n');
              const result = title.match(/Merge pull request #(.)/);
              if (result) {
                acc.push({
                  pullRequestNumber: result[1],
                  message: body[0],
                });
              }
              return acc;
            }, []);
            console.log(pullRequestList)